### ISSUE TITLE
Pre-stable features roadmap

### ISSUE THREAD

**Issue by marcosdly** [marcosdly/kepler.nvim#2]
- [ ] Keymap sequence not apprearing in status line
- [ ] oil.nvim preview on floating window
- [ ] oil.nvim project-drawer-like directory preview with decently complex depth constraints
- [ ] Robust and feature-full keymap searching and documentation (fuzzy, filtering, sorting)
- [ ] Editor-wise action fuzzy finder similar to vscode `<C-S-p>` pop menu
- [ ] Dap auto detection and loading of `.vscode/launch.json`
- [ ] Better support for `.vscode/launch.json` options support for dap
- [ ] Replace netrw with oil.nvim entirely
- [ ] Less colorful, better configurable version of `doom-one`
- [ ] Hard coded implementations of text editing convenience keymaps like `<C-BS>` for deleting previous word (not WORD)
- [ ] Awesome in-code documentation and static documentation generation
- [ ] Best CI practices (linting, formating)
- [ ] Custom core plugins loader (2 or more of same plugin with different versions)
- [ ] Auto setup (neovim as lua interpreter)
- [ ] Useful core plugins
- [ ] Less opinionated formatter than stylua (force `func"single arg".attr` style)
- [ ] Full support for `.editorconfig`
- [ ] Support for `.vscode/settings.json`
- [ ] Auto configure formatter.nvim
- [ ] Quick configuration center
- [ ] vscode-like configuration center based on lua_ls typing information with cached base on file `mtime` or `ctime`

### Eventually
- [ ] Reduce amount of plugins
- [ ] Better event-based plugin loading
- [ ] Optimize autocmds
- [ ] Try to enforce non-trivial declarative syntax where it could improve readability
